# Setup
title:               Ramblings & Reflections
tagline:             'Blog von Till Wagner'
description:         ''
url:                 https://www.tr-w.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Till Wagner
  url:               
  email:             tillwagner@mailbox.org
  instagram:         wirfandeneinenpfad


# Gems
plugins:
  - jekyll-paginate
  - jekyll-analytics


# Custom vars
google_analytics_id: G-DPLLG4R3WK

collections:
  - photo_gallery

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-DPLLG4R3WK         # Required - replace with your tracking id
    anonymizeIp: false  



