# Setup
title:               Ramblings & Reflections
tagline:             'Blog von Till Wagner'
description:         ''
url:                 www.tr-w.xyz
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Till Wagner
  url:               
  email:             tillwagner@mailbox.org
  instagram:         wirfandeneinenpfad


# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: G-DPLLG4R3WK

collections:
  - photo_gallery

