# Setup
title:               Eine Bewegung gegen den Fleiß
tagline:             'Blog von Till Wagner'
description:         ''
url:                 https://txt.tr-w.xyz
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Till Wagner
  url:               
  email:             tillwagner@mailbox.org
  instagram:         wirfandeneinenpfad

#Jekyll-Photo-Gallery Settings
exiftag:
 sources:
     - images/photography #Set to location of photos

# Gems
plugins:
  - jekyll-paginate
  - gem 'exifr'

# Custom vars
version:             1.1.0
google_analytics_id: 
